spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest-gift-certificates-security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: db
    schemas: rest-gift-certificates-security
    clean-disabled: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
jwt:
  expiration: 60
  issuer: epam
logging:
  level:
    org:
      springframework:
        security: trace